SELECT * FROM pg_user;

CREATE ROLE sa;

ALTER ROLE sa WITH PASSWORD 'uat2db@123';

ALTER ROLE sa WITH LOGIN;

ALTER ROLE sa WITH CREATEDB;

ALTER ROLE sa WITH CREATEROLE;

ALTER ROLE sa WITH SUPERUSER;

SELECT * FROM pg_user WHERE usename = 'sa';